apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp-deployment
  labels:
    app: pyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: 318988877498.dkr.ecr.us-east-2.amazonaws.com/pyapp
          ports:
            - containerPort: 8080
          resources:
            requests:
               memory: "128Mi" 
               cpu: "500m" 
            limits:
               memory: "500Mi"
               cpu: "1000m" 


---
apiVersion: v1
kind: Service
metadata:
  name: pyapp-nodeport-service
  labels:
    app: pyapp
spec:
  type: NodePort
  selector:
    app: pyapp
  ports:
    - port: 8080
      targetPort: 8080

